on:
  push:
    branches:  
      - main 
      - develop
      
  pull_request:
    branches:
      - main 
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Roman-Number

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8.0.332+9
        distribution: 'temurin'
        cache: 'maven'
      
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
        
    - name: Jacoco
      run: mvn test jacoco:report
    
    - name: 🚀 Coveralls Coverage Report Submission
      run: mvn coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
      
